AllCops:
  TargetRubyVersion: 2.1
Metrics/LineLength:
  Max: 180
Metrics/MethodLength:
  Max: 200
Metrics/BlockLength:
  Max: 30
Metrics/ParameterLists:
  Max: 8
Metrics/ClassLength:
  Max: 240
Metrics/AbcSize:
  Max: 42
Metrics/CyclomaticComplexity:
  Max: 8
  