name: GoLint

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.3
      - name: Install golangci-lint-action
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.1
          args: --timeout 5m
      - name: Run golangci-lint
        run: golangci-lint run
        