name: GoLint

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.3
      - name: Install GoLint
        run: go get -u golang.org/x/lint/golint
      - name: Run GoLint
        run: golangci-lint run
